-- Initiate with 30 students
insert into users (user_name, full_name) values ('wgherarducci0', 'Woodrow Gherarducci');
insert into users (user_name, full_name) values ('adundendale1', 'Agatha Dundendale');
insert into users (user_name, full_name) values ('ccoombes2', 'Cristin Coombes');
insert into users (user_name, full_name) values ('aperillio3', 'Alexis Perillio');
insert into users (user_name, full_name) values ('crivaland4', 'Cindra Rivaland');
insert into users (user_name, full_name) values ('raylmore5', 'Raynell Aylmore');
insert into users (user_name, full_name) values ('tmcgeoch6', 'Taryn McGeoch');
insert into users (user_name, full_name) values ('dsailes7', 'Dorian Sailes');
insert into users (user_name, full_name) values ('rplak8', 'Rosco Plak');
insert into users (user_name, full_name) values ('pmizen9', 'Paxton Mizen');
insert into users (user_name, full_name) values ('kmacillricka', 'Kathi MacIllrick');
insert into users (user_name, full_name) values ('tscamerdenb', 'Tad Scamerden');
insert into users (user_name, full_name) values ('ngatrellc', 'Nilson Gatrell');
insert into users (user_name, full_name) values ('schartresd', 'Starr Chartres');
insert into users (user_name, full_name) values ('fmeire', 'Franciskus Meir');
insert into users (user_name, full_name) values ('mschmuhlf', 'Millisent Schmuhl');
insert into users (user_name, full_name) values ('llummasanag', 'Lynde Lummasana');
insert into users (user_name, full_name) values ('gmccaddenh', 'Gwennie McCadden');
insert into users (user_name, full_name) values ('llandsbergi', 'Lambert Landsberg');
insert into users (user_name, full_name) values ('mrieplj', 'Maribeth Riepl');
insert into users (user_name, full_name) values ('bcanok', 'Benn Cano');
insert into users (user_name, full_name) values ('rswadlingl', 'Roby Swadling');
insert into users (user_name, full_name) values ('bdem', 'Broddie De Rechter');
insert into users (user_name, full_name) values ('checknern', 'Corty Heckner');
insert into users (user_name, full_name) values ('ymorado', 'Yorke Morad');
insert into users (user_name, full_name) values ('bdowdap', 'Brandy Dowda');
insert into users (user_name, full_name) values ('aveyseyq', 'Analiese Veysey');
insert into users (user_name, full_name) values ('dhatherallr', 'Daphne Hatherall');
insert into users (user_name, full_name) values ('jcloughs', 'Joeann Clough');
insert into users (user_name, full_name) values ('hmorigant', 'Harriett Morigan');

insert into user_role (role_id, user_id) values (3, 1);
insert into user_role (role_id, user_id) values (3, 2);
insert into user_role (role_id, user_id) values (3, 3);
insert into user_role (role_id, user_id) values (3, 4);
insert into user_role (role_id, user_id) values (3, 5);
insert into user_role (role_id, user_id) values (3, 6);
insert into user_role (role_id, user_id) values (3, 7);
insert into user_role (role_id, user_id) values (3, 8);
insert into user_role (role_id, user_id) values (3, 9);
insert into user_role (role_id, user_id) values (3, 10);
insert into user_role (role_id, user_id) values (3, 11);
insert into user_role (role_id, user_id) values (3, 12);
insert into user_role (role_id, user_id) values (3, 13);
insert into user_role (role_id, user_id) values (3, 14);
insert into user_role (role_id, user_id) values (3, 15);
insert into user_role (role_id, user_id) values (3, 16);
insert into user_role (role_id, user_id) values (3, 17);
insert into user_role (role_id, user_id) values (3, 18);
insert into user_role (role_id, user_id) values (3, 19);
insert into user_role (role_id, user_id) values (3, 20);
insert into user_role (role_id, user_id) values (3, 21);
insert into user_role (role_id, user_id) values (3, 22);
insert into user_role (role_id, user_id) values (3, 23);
insert into user_role (role_id, user_id) values (3, 24);
insert into user_role (role_id, user_id) values (3, 25);
insert into user_role (role_id, user_id) values (3, 26);
insert into user_role (role_id, user_id) values (3, 27);
insert into user_role (role_id, user_id) values (3, 28);
insert into user_role (role_id, user_id) values (3, 29);
insert into user_role (role_id, user_id) values (3, 30);

-- insert into classes (class_id, teacher_id, title, code, status, created_at, student_count) values (1, 2, 'Zoolab', 'Uq3dT', 'inactive', '2023-09-16 16:09:43', 42);
-- insert into classes (class_id, teacher_id, title, code, status, created_at, student_count) values (2, 2, 'Vagram', 'VgUu2', 'active', '2023-03-28 10:23:09', 31);
-- insert into classes (class_id, teacher_id, title, code, status, created_at, student_count) values (3, 2, 'Span', 'a5VrY', 'active', '2023-01-21 00:14:12', 13);
-- insert into classes (class_id, teacher_id, title, code, status, created_at, student_count) values (4, 2, 'Greenlam', 'zJXRY', 'inactive', '2023-10-18 12:13:40', 44);
